# Generated by Django 5.2.7 on 2026-02-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_remove_invoice_due_date_remove_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
