# Generated by Django 5.2.7 on 2026-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='brand_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
