"""
Django settings for INVOICES project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file at the project root
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from .env file — never hardcode this in source code
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Reads 'True'/'False' string from .env and converts to Python boolean
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Allowed hostnames — loaded from comma-separated .env value
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost').split(',')


# Application definition

# All Django apps and third-party packages used in the project
INSTALLED_APPS = [
    # --- Project apps (listed first so our templates/static take priority) ---
    'core.apps.CoreConfig',              # Shared base models and template tags
    'accounts.apps.AccountsConfig',      # Custom user model and authentication
    'businesses.apps.BusinessesConfig',  # Business profiles and management
    'billings.apps.BillingsConfig',      # Invoices, clients, milestones
    # --- Third-party apps ---
    'rest_framework',                    # Django REST Framework — API views, serializers, routers
    'rest_framework_simplejwt',          # JWT authentication for API endpoints
    'corsheaders',                       # Cross-Origin Resource Sharing (allows React frontend to call API)
    # --- Django built-in apps ---
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Provides template filters like intcomma, naturaltime
    'drf_spectacular',          # OpenAPI schema generation for DRF (optional, but useful for API docs)
]

# Middleware runs on every request/response cycle (order matters!)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # HTTPS redirects, HSTS headers
    'whitenoise.middleware.WhiteNoiseMiddleware',              # Serve static files via Gunicorn/WSGI
    'corsheaders.middleware.CorsMiddleware',                   # CORS — must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',    # Enables session support
    'django.middleware.common.CommonMiddleware',               # URL normalization (trailing slashes)
    'django.middleware.csrf.CsrfViewMiddleware',               # Cross-Site Request Forgery protection
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Attaches request.user
    'django.contrib.messages.middleware.MessageMiddleware',    # Flash messages framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Prevents clickjacking via X-Frame-Options
]

ROOT_URLCONF = 'config.urls'

# Template engine configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Project-level templates (base.html, index.html)
        'APP_DIRS': True,                  # Also look in each app's templates/ folder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',    # Makes 'request' available in templates
                'django.contrib.auth.context_processors.auth',   # Makes 'user' and 'perms' available
                'django.contrib.messages.context_processors.messages',  # Flash messages
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Credentials loaded from .env — never hardcode passwords in source code
# If DATABASE_URL is set (e.g., in Docker), use it; otherwise fall back to individual vars
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(os.getenv('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': int(os.getenv('DB_PORT', '5432')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'               # URL prefix for static files (CSS, JS, images)
STATICFILES_DIRS = [
    BASE_DIR / 'static',              # Additional static files directory (dev)
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic gathers files for production

# WhiteNoise — serves static files efficiently in production (Gunicorn)
# Compresses and caches static files with unique hashes for cache-busting
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads like logos and profile images)
MEDIA_URL = '/media/'                 # URL prefix for user-uploaded files
MEDIA_ROOT = BASE_DIR / 'media'       # Filesystem path for uploaded files

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model — tells Django to use our UUID-based user instead of auth.User
AUTH_USER_MODEL = 'accounts.CustomUser'

# Login/Logout URLs — controls where Django redirects for auth
LOGIN_URL = 'accounts:login'           # Redirect here when @login_required fails
LOGIN_REDIRECT_URL = 'home'            # After successful login, go to dashboard
LOGOUT_REDIRECT_URL = 'accounts:login' # After logout, go back to login page

# Email Configuration (Development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# For production, use SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'


# =============================================================
# Django REST Framework (DRF) Configuration
# Provides API views, serializers, authentication, and browsable API
# =============================================================
REST_FRAMEWORK = {
    # Default authentication — JWT for API clients, session for browsable API
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Token-based auth for API
        'rest_framework.authentication.SessionAuthentication',        # Cookie-based auth for browsable API
    ),
    # Default permissions — all endpoints require authentication unless overridden
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Pagination — return 20 items per page by default
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # For OpenAPI schema generation
}


# =============================================================
# Simple JWT Configuration
# JSON Web Token settings for API authentication
# Clients send: Authorization: Bearer <access_token>
# =============================================================
from datetime import timedelta  # Required for token lifetime durations

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),   # Access token expires in 30 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),      # Refresh token expires in 1 day
    'ROTATE_REFRESH_TOKENS': True,                    # Issue new refresh token on each refresh
    'BLACKLIST_AFTER_ROTATION': True,                 # Invalidate old refresh token after rotation
    'AUTH_HEADER_TYPES': ('Bearer',),                 # Expected header: Authorization: Bearer <token>
}


# =============================================================
# CORS (Cross-Origin Resource Sharing) Configuration
# Controls which external domains can call your API
# Required when React frontend runs on a different port/domain
# =============================================================
# In development, allow the React dev server
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
# Allow cookies/auth headers in cross-origin requests
CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins — required when using session auth behind a reverse proxy
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')


# =============================================================
# Production Security Settings
# Activated when DEBUG=False (production environment)
# =============================================================
if not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000       # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'


# =============================================================
# Logging Configuration
# Logs are written to the /logs directory (gitignored).
# Four log files, each serving a different purpose:
#   - general.log   → all INFO+ messages from our project code
#   - errors.log    → only WARNING+ from everywhere (good for monitoring)
#   - security.log  → auth events (login attempts, permission denied, etc.)
#   - debug.log     → everything DEBUG+ (verbose, development only)
# =============================================================
LOG_DIR = BASE_DIR / 'logs'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Keep Django's default loggers active

    # --- Formatters: control how each log line looks ---
    'formatters': {
        # Full format with timestamp, level, module, and message
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} — {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Compact format for console output
        'simple': {
            'format': '{levelname} {name} — {message}',
            'style': '{',
        },
    },

    # --- Handlers: destinations where log messages are sent ---
    'handlers': {
        # Console output (always active) — shows simple format in terminal
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        # General log — captures all INFO+ from project apps
        'general_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'general.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB per file
            'backupCount': 5,              # Keep 5 rotated backups
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Error log — captures WARNING+ from all sources
        'error_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Security log — captures auth-related events (login, permission denied)
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'security.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # Debug log — captures everything (verbose, development only)
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'debug.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB (debug is chatty)
            'backupCount': 3,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },

    # --- Loggers: named channels that route messages to handlers ---
    'loggers': {
        # Django's internal logger — errors go to error file + console
        'django': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django request handling — logs 4xx/5xx HTTP errors
        'django.request': {
            'handlers': ['error_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django security — CSRF failures, suspicious operations
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Database queries — useful for debugging slow queries (set DEBUG to see SQL)
        'django.db.backends': {
            'handlers': ['debug_file'],
            'level': 'WARNING',  # Set to DEBUG to log all SQL queries
            'propagate': False,
        },
        # --- Project app loggers (use these in your code) ---
        # Usage: import logging; logger = logging.getLogger(__name__)
        'accounts': {
            'handlers': ['general_file', 'security_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'billings': {
            'handlers': ['general_file', 'error_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'businesses': {
            'handlers': ['general_file', 'error_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'config': {
            'handlers': ['general_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
